spring.application.name=javitasnyilntarto
spring.datasource.url=jdbc:postgresql://localhost:5432/jewelrepairstore
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true
logging.level.org.hibernate.sql=DEBUG
logging.level.org.hibernate.type=TRACE
spring.awt.headless=true
logging.level.otvosuzlet.javitasnyilntarto=DEBUG
server.error.include-stacktrace=always
spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB
server.servlet.session.timeout=2d
server.error.path=/api/error
spring.jackson.time-zone=Europe/Budapest
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Budapest
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
app.image.directory=job-images

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost,http://192.168.1.6:4200,http://192.168.1.6}

# JWT TTLs
jwt.access-token-ttl-ms=${JWT_ACCESS_TOKEN_TTL_MS:500000}
jwt.refresh-token-ttl-ms=${JWT_REFRESH_TOKEN_TTL_MS:864000000}

# In production set env var JWT_SECRET_BASE64 to a strong random Base64 value (>= 32 bytes).
#jwt.secret-base64=${JWT_SECRET_BASE64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB=}